// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherUserActions.Data;

#nullable disable

namespace WeatherUserActions.Migrations
{
    [DbContext(typeof(WeatherUserActionsDbContext))]
    partial class WeatherUserActionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherUserActions.Models.AnalyticsReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Cities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateRangeEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateRangeStart")
                        .HasColumnType("date");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("AnalyticsReports");
                });

            modelBuilder.Entity("WeatherUserActions.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities", t =>
                        {
                            t.HasCheckConstraint("CK_Cities_Latitude", "[Latitude] >= -90 AND [Latitude] <= 90");

                            t.HasCheckConstraint("CK_Cities_Longitude", "[Longitude] >= -180 AND [Longitude] <= 180");
                        });
                });

            modelBuilder.Entity("WeatherUserActions.Models.CitySite", b =>
                {
                    b.Property<int>("CitySiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitySiteId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("CitySiteId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("CityId", "ServiceId")
                        .IsUnique();

                    b.ToTable("CitySites");
                });

            modelBuilder.Entity("WeatherUserActions.Models.Forecast", b =>
                {
                    b.Property<int>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForecastId"));

                    b.Property<int>("CitySiteId")
                        .HasColumnType("int");

                    b.Property<bool>("DangerFlag")
                        .HasColumnType("bit");

                    b.Property<decimal>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("WindSpeed")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ForecastId");

                    b.HasIndex("CitySiteId", "Timestamp", "Type")
                        .IsUnique();

                    b.ToTable("Forecasts", t =>
                        {
                            t.HasCheckConstraint("CK_Forecasts_Humidity", "[Humidity] >= 0 AND [Humidity] <= 100");

                            t.HasCheckConstraint("CK_Forecasts_Temperature", "[Temperature] >= -90 AND [Temperature] <= 60");

                            t.HasCheckConstraint("CK_Forecasts_WindSpeed", "[WindSpeed] >= 0 AND [WindSpeed] <= 253");
                        });
                });

            modelBuilder.Entity("WeatherUserActions.Models.ForecastingService", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.ToTable("ForecastingServices");
                });

            modelBuilder.Entity("WeatherUserActions.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForecastId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("ForecastId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WeatherUserActions.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ForecastId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("ForecastId");

                    b.HasIndex("UserId", "ForecastId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("WeatherUserActions.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WeatherUserActions.Models.UserCitySite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CitySiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "CitySiteId");

                    b.HasIndex("CitySiteId");

                    b.ToTable("UserCitySites");
                });

            modelBuilder.Entity("WeatherUserActions.Models.UserService", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("UserServices");
                });

            modelBuilder.Entity("WeatherUserActions.Models.AnalyticsReport", b =>
                {
                    b.HasOne("WeatherUserActions.Models.User", "User")
                        .WithMany("AnalyticsReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeatherUserActions.Models.CitySite", b =>
                {
                    b.HasOne("WeatherUserActions.Models.City", "City")
                        .WithMany("CitySites")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherUserActions.Models.ForecastingService", "Service")
                        .WithMany("CitySites")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("WeatherUserActions.Models.Forecast", b =>
                {
                    b.HasOne("WeatherUserActions.Models.CitySite", "CitySite")
                        .WithMany("Forecasts")
                        .HasForeignKey("CitySiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitySite");
                });

            modelBuilder.Entity("WeatherUserActions.Models.Notification", b =>
                {
                    b.HasOne("WeatherUserActions.Models.Forecast", "Forecast")
                        .WithMany("Notifications")
                        .HasForeignKey("ForecastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherUserActions.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forecast");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeatherUserActions.Models.Rating", b =>
                {
                    b.HasOne("WeatherUserActions.Models.Forecast", "Forecast")
                        .WithMany("Ratings")
                        .HasForeignKey("ForecastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherUserActions.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forecast");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeatherUserActions.Models.UserCitySite", b =>
                {
                    b.HasOne("WeatherUserActions.Models.CitySite", "CitySite")
                        .WithMany("UserCitySites")
                        .HasForeignKey("CitySiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherUserActions.Models.User", "User")
                        .WithMany("UserCitySites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CitySite");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeatherUserActions.Models.UserService", b =>
                {
                    b.HasOne("WeatherUserActions.Models.ForecastingService", "Service")
                        .WithMany("UserServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherUserActions.Models.User", "User")
                        .WithMany("UserServices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeatherUserActions.Models.City", b =>
                {
                    b.Navigation("CitySites");
                });

            modelBuilder.Entity("WeatherUserActions.Models.CitySite", b =>
                {
                    b.Navigation("Forecasts");

                    b.Navigation("UserCitySites");
                });

            modelBuilder.Entity("WeatherUserActions.Models.Forecast", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("WeatherUserActions.Models.ForecastingService", b =>
                {
                    b.Navigation("CitySites");

                    b.Navigation("UserServices");
                });

            modelBuilder.Entity("WeatherUserActions.Models.User", b =>
                {
                    b.Navigation("AnalyticsReports");

                    b.Navigation("Notifications");

                    b.Navigation("Ratings");

                    b.Navigation("UserCitySites");

                    b.Navigation("UserServices");
                });
#pragma warning restore 612, 618
        }
    }
}
